set -g mouse on
set -g extended-keys on
set -s set-clipboard on
set-window-option -g mode-keys vi
set -as terminal-overrides ',alacritty:Ms=\E]52;c;%p2%s\7'

# Copy mode bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

bind-key -n MouseDown2Pane run-shell -b "xclip -o | tmux load-buffer - && tmux paste-buffer"
